apiVersion: authorino.kuadrant.io/v1beta1
kind: AuthConfig
metadata:
  name: news-api-protection
spec:
  hosts:
  - news-api.127.0.0.1.nip.io

  identity:
  - name: api-key-users
    apiKey:
      selector: {}
    credentials:
      keySelector: APIKEY
    extendedProperties:
      - name: username
        valueFrom: { authJSON: auth.identity.metadata.annotations.username }
      - name: name
        valueFrom: { authJSON: auth.identity.metadata.annotations.name }
  - name: keycloak-users
    oidc:
      endpoint: http://keycloak.keycloak.svc.cluster.local:8080/realms/devconf
    extendedProperties:
      - name: username
        valueFrom: { authJSON: auth.identity.preferred_username }
      - name: name
        valueFrom: { authJSON: auth.identity.name }

  authorization:
  - name: k8s-rbac
    kubernetes:
      user:
        valueFrom:
          authJSON: auth.identity.username
      resourceAttributes:
        namespace:
          value: news-api
        group:
          value: news-api
  - name: email-verified
    when:
    - selector: auth.identity.typ
      operator: eq
      value: Bearer
    json:
      rules:
      - selector: auth.identity.email_verified
        operator: eq
        value: "true"

  response:
  - name: x-ext-auth-data
    json:
      properties:
      - name: author
        valueFrom: { authJSON: auth.identity.name }
      - name: user_id
        valueFrom: { authJSON: auth.identity.username }
